
services:
  # Serwer MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_api
    environment:
      MYSQL_ROOT_PASSWORD: shop      # Hasło roota
      MYSQL_DATABASE: shop    # Nazwa domyślnej bazy danych
      MYSQL_USER: shop               # Nazwa użytkownika
      MYSQL_PASSWORD: shop       # Hasło użytkownika
    volumes:
      - db-data:/var/lib/mysql       # Dane przechowywane na wolumenie
    ports:
      - "3306:3306"                 # Mapowanie portu MySQL
    # restart: always

  # Serwer PHP
  php:
    build:
        context: ./docker/php
    container_name: php_api
    volumes:
      - ./:/var/www/html          # Montowanie aplikacji z lokalnego folderu
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "~/.ssh:/root/.ssh"
    # restart: always
    depends_on:
      - mysql                        # Uruchamia się po MySQL

  # Serwer Nginx
  nginx:
    image: nginx:1.21-alpine         # Używamy lekkiej wersji Nginx z Alpine
    container_name: nginx_api
    volumes:
      - ./:/var/www/html          # Montowanie aplikacji z lokalnego folderu
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf  # Montowanie pliku konfiguracyjnego Nginx
    ports:
      - "80:80"                      # Mapowanie portu HTTP
    # restart: always
    depends_on:
      - php                          # Uruchamia się po PHP
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  

volumes:
  db-data:                           # Definicja wolumenu dla danych MySQL
  db-data-test:                      # Definicja wolumenu dla danych MySQL
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
